name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    name: Build and Upload Release
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: raytracer-linux-amd64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: raytracer-windows-amd64.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: raytracer-macos-amd64

    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build Binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload Binary to GitHub Release
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: raytracer
          target: ${{ matrix.target }}
          token: ${{ secrets.GITHUB_TOKEN }}
